version: '3.8'

services:
  nodejs12.x:
    command: sh -c "[ -f 'package.json' ] && npm install || echo No package.json found"
    image: node:12-alpine
    volumes:
      - $DIR:/app
    working_dir: /app
